Import ncp3-gate 3dfbb51139c9 134c finalized bkport-400aca678a81-pcieb-bogus-message-fix.patch bkport-4d28e30f7dd0-e1000g-bug-fixes.patch bkport-5bcd281629f8-zfs-dev-removal-fix.patch bkport-6d20da30d725-comstar-scsi-rw-verify-support.patch bkport-75c1100ead0b-si3124.patch bkport-78579915ae6d-pcitool-fix.patch bkport-7b0bf7ecf3db-devfsadm-device-node.patch bkport-9332ab22b7ba-mr-sas.patch bkport-995e603fdf81-zfs-mlslabel.patch bkport-dba4b8072daa-ixgbe-link-fix.patch bkport-f13874aa8143-qlc-update.patch bkport-reworked-ba3f66213a3a-qlc-update.patch status

diff --git a/usr/src/pkgdefs/SUNW1394/postinstall b/usr/src/pkgdefs/SUNW1394/postinstall
--- a/usr/src/pkgdefs/SUNW1394/postinstall
+++ b/usr/src/pkgdefs/SUNW1394/postinstall
@@ -93,10 +93,8 @@ grep "^${DRV} " $BASEDIR/etc/name_to_major > /dev/null 2>&1
 if [ $? -ne 0 ]; then
 	${ADD_DRV} -m "${DRVPERM}" -i "\"${DRVALIAS}\"" ${DRV}
 	if [ $? -ne 0 ]; then
-		echo
-		echo "Failed add_drv of ${DRV}!" >&2
-		# do not fail upgrade
-		exit 0
+		echo "\nFailed add_drv of ${DRV}!\n" >&2
+		exit 1
 	fi
 fi
 
diff --git a/usr/src/pkgdefs/SUNWatheros/postremove b/usr/src/pkgdefs/SUNWatheros/postremove
--- a/usr/src/pkgdefs/SUNWatheros/postremove
+++ b/usr/src/pkgdefs/SUNWatheros/postremove
@@ -43,6 +43,10 @@ fi
 /usr/bin/egrep -s "^${DRV}[ 	]" $BASEDIR/etc/name_to_major
 if [ $? -eq 0 ]; then
 	${REM_DRV} ${DRV}
+        if [ $? -ne 0 ]; then
+		echo "Failed rem_drv ${DRV}!\n" >&2
+                exit 1
+        fi
 fi
 
 exit 0
diff --git a/usr/src/pkgdefs/SUNWiiu/preremove b/usr/src/pkgdefs/SUNWiiu/preremove
--- a/usr/src/pkgdefs/SUNWiiu/preremove
+++ b/usr/src/pkgdefs/SUNWiiu/preremove
@@ -104,8 +104,8 @@ then
 	modunload -i ${MODID}
 	if [ $? != 0 ]
 	then
-		echo "Warning: Failed to unload $MODULE module."
-		exit 0
+		echo "Error: Failed to unload $MODULE module."
+		exit 1
 	fi
 fi
 fi
diff --git a/usr/src/pkgdefs/SUNWscmu/preremove b/usr/src/pkgdefs/SUNWscmu/preremove
--- a/usr/src/pkgdefs/SUNWscmu/preremove
+++ b/usr/src/pkgdefs/SUNWscmu/preremove
@@ -35,7 +35,7 @@ export PATH
 DEVLINKTB="${PKG_INSTALL_ROOT}/etc/devlink.tab"
 FAILURE=1
 NAMEMAJOR="${PKG_INSTALL_ROOT}/etc/name_to_major"
-PKG_INSTALL_ROOT=/etc/..
+PKG_INSTALL_ROOT=${PKG_INSTALL_ROOT:=/}
 # reconfig order
 CFGMODULES="nskern ncall nsctl sdbc"
 # reverse dependency order
@@ -112,7 +112,7 @@ do
 	    ${REM_DRV} ${MODULE} > ${ERRLOG} 2>&1
 	    [ $? -ne 0 ] && {
 		message ${REMOVERR}
-		exit 0
+		exit ${FAILURE}
 	    } 
 	fi
 
@@ -128,8 +128,8 @@ do
  		modunload -i ${MODID}
  		if [ $? -ne 0 ]
  		then
- 			echo "Warning: Failed to unload $MODULE module."
- 			exit 0
+ 			echo "Error: Failed to unload $MODULE module."
+ 			exit 1
  		fi
  	fi
  	fi
@@ -146,7 +146,7 @@ then
 	if [ $? -ne 0 ]
 	then
 		echo "Warning: Failed to unload spuni module."
-		exit 0
+		exit 1
 	fi
 fi
 fi
diff --git a/usr/src/pkgdefs/SUNWsmbsu/preremove b/usr/src/pkgdefs/SUNWsmbsu/preremove
--- a/usr/src/pkgdefs/SUNWsmbsu/preremove
+++ b/usr/src/pkgdefs/SUNWsmbsu/preremove
@@ -35,7 +35,8 @@ if [ "${PKG_INSTALL_ROOT:-/}" = "/" ]; then
 	do
 		/usr/bin/pgrep -x -u 0 "$i" >/dev/null
 		if [ $? -ne 1 ]; then
-			echo "Warning: $i is still running"
+			echo "$i running; unable to remove package"
+			exit 1
 		fi
 	done
 fi
diff --git a/usr/src/pkgdefs/SUNWspsvu/preremove b/usr/src/pkgdefs/SUNWspsvu/preremove
--- a/usr/src/pkgdefs/SUNWspsvu/preremove
+++ b/usr/src/pkgdefs/SUNWspsvu/preremove
@@ -37,7 +37,7 @@ export PATH
 DEVLINKTB="${PKG_INSTALL_ROOT}/etc/devlink.tab"
 MODULE="sv"
 NAMEMAJOR="${PKG_INSTALL_ROOT}/etc/name_to_major"
-PKG_INSTALL_ROOT=/etc/..
+PKG_INSTALL_ROOT=${PKG_INSTALL_ROOT:=/}
 TMP=/tmp/${PKGINST}.$$
 SVC=nws_sv
 FS_LOCAL_SVC="svc:/system/filesystem/local"
@@ -108,8 +108,8 @@ then
 	modunload -i ${MODID}
 	if [ $? != 0 ]
 	then
-		echo "Warning: Failed to unload $MODULE module."
-		exit 0
+		echo "Error: Failed to unload $MODULE module."
+		exit 1
 	fi
 fi
 fi
